### ISSUE TITLE
Aeryn is inviting people who are already members

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/peril-settings#5]
Example: https://github.com/ashfurrow/danger-ruby-swiftlint/pull/83#issuecomment-356044529

**Comment by ashfurrow** [comment]
lol sob

**Comment by thii** [comment]
I was invited to https://github.com/ashfurrow/danger-swiftlint, maybe because it’s the old URL?

**Comment by ashfurrow** [comment]
Ahhhhh haha yeah that's definitely it. I think Peril was using your fork's old (and now re-used) name 😄  That solves that mystery, thank you! Now I just need to find out what's going on with the comment above ^
